!!python/object:ml_collections.config_dict.config_dict.ConfigDict
_convert_dict: true
_fields:
  experiment: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      batch_size: 100
      chain_length: 100000
      ess_ratio: 0.5
      evaluator: ess_eval
      fig_folder: /gcs/xcloud-shared/kgoshvadi/results/discs/discs-ising-sampler_sweep_56214850/13_sampler_config.name='path_auxiliary',model_config.mu=1,model_config.lambdaa=1,model_config.init_sigma=3,sampler_config.balancing_fn_type='SQRT'/logs/figures
      get_additional_metrics: false
      log_every_steps: 100
      name: Sampling_Experiment
      num_models: 1
      plot_every_steps: 10
      run_parallel: true
      save_every_steps: 10000
      save_root: /gcs/xcloud-shared/kgoshvadi/results/discs/discs-ising-sampler_sweep_56214850/13_sampler_config.name='path_auxiliary',model_config.mu=1,model_config.lambdaa=1,model_config.init_sigma=3,sampler_config.balancing_fn_type='SQRT'
      shuffle_buffer_size: 0
      use_tqdm: false
    _locked: false
    _type_safe: true
  model: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      data_root: sco
      external_field_type: 1
      init_sigma: 3.0
      lambdaa: 1.0
      mu: 1.0
      name: ising
      num_categories: 2
      save_dir_name: ising_hightemp
      shape: !!python/tuple
      - 50
      - 50
    _locked: false
    _type_safe: true
  sampler: !!python/object:ml_collections.config_dict.config_dict.ConfigDict
    _convert_dict: true
    _fields:
      adaptive: true
      balancing_fn_type: SQRT
      name: path_auxiliary
      num_flips: 1
      target_acceptance_rate: 0.574
      use_fast_path: true
    _locked: false
    _type_safe: true
_locked: false
_type_safe: true
